// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAytMPYfPOukhMZMjOccPgTipzgYiBqGJU',
    appId: '1:935747436852:web:9586a8397110bcb2fca561',
    messagingSenderId: '935747436852',
    projectId: 'tmovie-7014c',
    authDomain: 'tmovie-7014c.firebaseapp.com',
    storageBucket: 'tmovie-7014c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANtdZZDR4qv7nmganWfe09op2RCeG_BhQ',
    appId: '1:935747436852:android:0bb2a37a6ee7902ffca561',
    messagingSenderId: '935747436852',
    projectId: 'tmovie-7014c',
    storageBucket: 'tmovie-7014c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBDTOaWZVMep6oxcelzbvvQLy1Z46Imxo',
    appId: '1:935747436852:ios:0f5bc52b251d6f34fca561',
    messagingSenderId: '935747436852',
    projectId: 'tmovie-7014c',
    storageBucket: 'tmovie-7014c.firebasestorage.app',
    iosBundleId: 'com.example.tmovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBDTOaWZVMep6oxcelzbvvQLy1Z46Imxo',
    appId: '1:935747436852:ios:0f5bc52b251d6f34fca561',
    messagingSenderId: '935747436852',
    projectId: 'tmovie-7014c',
    storageBucket: 'tmovie-7014c.firebasestorage.app',
    iosBundleId: 'com.example.tmovie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAytMPYfPOukhMZMjOccPgTipzgYiBqGJU',
    appId: '1:935747436852:web:ec5fc059c6ed7f30fca561',
    messagingSenderId: '935747436852',
    projectId: 'tmovie-7014c',
    authDomain: 'tmovie-7014c.firebaseapp.com',
    storageBucket: 'tmovie-7014c.firebasestorage.app',
  );
}
